export type Locale = 'en' | 'zh' | 'id' | 'th' | 'vi'

export const LOCALES: { code: Locale; label: string; short: string }[] = [
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'zh', label: '简体中文', short: '中文' },
  { code: 'id', label: 'Bahasa Indonesia', short: 'ID' },
  { code: 'th', label: 'ภาษาไทย', short: 'TH' },
  { code: 'vi', label: 'Tiếng Việt', short: 'VI' },
]

export const DEFAULT_LOCALE: Locale = 'en'

type Step = { title: string; desc: string; tools: string[] }
type Shot = { time: string; shot: string; caption: string }
type MarketingPlan = {
  name: string
  price: string
  unit: string
  desc: string
  features: string[]
  cta: string
}
type AccountPlan = {
  name: string
  description: string
  cta: string
  features: string[]
}

// ---------------------------------------------------------------------------
// English (default / source)
// ---------------------------------------------------------------------------
const en = {
  lang: { label: 'Language' },
  nav: { workflow: 'Workflow', preview: 'Preview', models: 'AI Models', pricing: 'Pricing' },
  transition: {
    auth: { title: 'Signing you in', description: 'Verifying your details and preparing your workspace…', trust: 'Your account is protected' },
    checkout: { title: 'Preparing secure checkout', description: 'Creating your private Stripe checkout session…', trust: 'Securely processed by Stripe' },
    portal: { title: 'Opening billing center', description: 'Connecting securely to your subscription settings…', trust: 'Securely processed by Stripe' },
    loading: { title: 'Getting things ready', description: 'Loading your Clipairy workspace…', trust: 'Secure connection' },
    errorTitle: 'We could not complete that step',
    authError: 'Please check your details and try again.',
    checkoutError: 'The secure payment page could not be opened. Please try again.',
    retry: 'Try again',
    home: 'Return home',
  },
  header: {
    signIn: 'Sign in',
    signUp: 'Sign up free',
    account: 'My account',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    mainNav: 'Main navigation',
    mobileNav: 'Mobile navigation',
  },
  hero: {
    badge: 'Built for cross-border e-commerce & TikTok Shop sellers',
    titleLine1: 'Turn viral video structures',
    titleHighlight: 'into ads for your product',
    subtitle:
      'Upload one viral reference video, then your product assets. AI breaks down the winning framework, rewrites the script, generates new footage and voiceover — a TikTok / Reels / Shorts ad in 5 minutes.',
    ctaStart: 'Start creating free',
    ctaPreview: 'See a sample result',
    exportTo: 'Export to',
    phoneAlt: 'Preview of a vertical product ad generated by Clipairy',
    phoneBadge: 'AI generated · Vertical 9:16',
  },
  studio: {
    title: 'Upload in 3 steps, AI handles the rest',
    subtitle:
      'Add a viral reference, your product assets, and key selling points — hit generate and watch the 12-step workflow run in real time.',
    upload1Label: '1 · Reference viral video',
    upload1Hint: 'Drop in a TikTok / Reels / Shorts video',
    upload2Label: '2 · Your product assets',
    upload2Hint: 'Upload product photos or videos',
    upload3Label: '3 · Selling points',
    sellingPlaceholder:
      'e.g. gentle plant-based formula, results in 7 days, free worldwide shipping, limited BOGO deal…',
    uploaded: 'Uploaded',
    creator: {
      characterTitle: 'On-screen talent', characterDesc: 'Choose a preset or upload an authorized photo. We will aim to keep the same person throughout.', characterDrift: 'AI may introduce slight facial or wardrobe drift', characterSelect: 'Choose on-screen talent', characterAlt: 'character reference', uploadCharacter: 'Upload my talent', authorization: 'Only yourself or authorized photos · JPG/PNG/WebP · 10 MB', qualityTitle: 'Video quality', qualityNames: { economy: 'Economy', standard: 'Standard', premium: 'Premium' }, qualityDescriptions: { economy: 'Fast and low-cost for testing ideas', standard: 'Balanced clarity and cost for daily publishing', premium: 'Stronger motion and visuals for flagship ads' }, per8: 'per 8s', credits: 'credits', modelApprox: 'model approx.', estimate: 'Estimated for {duration}s: {credits} credits, video model approx. ${cost}; excludes storyboard images, voice, storage, and retries.',
    },
    gateAnonTitle: 'Sign in and buy a plan to try generation',
    gateAnonDesc: 'Trial generation is only available to users with an active plan. Please sign in or register first.',
    gateNoPlanTitle: 'Buy a plan to unlock trial credits',
    gateNoPlanDesc:
      'You have no credits available. Choose any plan to start generating — credits are used up as you go.',
    buyPlan: 'Get a plan',
    durationLabel: 'Video duration',
    secondsUnit: 's',
    durationHint: 'Every finished video uses 1 credit. Longer videos combine multiple AI-generated clips.',
    aspectRatioLabel: 'Video format',
    portrait: 'Portrait',
    landscape: 'Landscape',
    statusIdle: 'Ready — click generate to start the 12-step automation',
    statusRunning: 'Processing…',
    statusDone: 'Done! Scroll down for the script, storyboard and video preview',
    stepStatus: { done: 'Done', processing: 'Processing', waiting: 'Waiting' },
    statusError: 'Generation failed',
    retry: 'Try again',
    errorTitle: 'Something went wrong',
    errorDesc: 'The generation could not be completed. Please try again.',
    sceneLabel: 'Scene ',
    voiceoverHeading: 'AI voiceover',
    creditsLabel: 'Credits left:',
    unlimited: 'Unlimited',
    regenerate: 'Generate again',
    generate: 'Generate video',
    generating: 'Generating…',
    workflowHeading: '12-step automated workflow',
    resultsPlaceholder:
      'Your results (script / storyboard / video preview) will appear here once the workflow completes',
    resultBadge: 'Generation complete',
    resultTitle: 'Your product ad is ready',
    scriptHeading: 'Rewritten ad script',
    storyboardHeading: 'Storyboard',
    captionLabel: 'Caption:',
    videoAlt: 'Preview of the AI-generated vertical product ad',
    exportButton: 'Export final cut',
    steps: [
      { title: 'Upload reference video', desc: 'Import the viral TikTok / Reels / Shorts video you want to model', tools: ['Uploader', 'S3 / R2 / Supabase Storage'] },
      { title: 'Video preprocessing', desc: 'Automatically split audio, frames and original caption tracks', tools: ['FFmpeg', 'MoviePy'] },
      { title: 'Extract copy', desc: 'Transcribe all narration, voiceover and captions into text', tools: ['gpt-4o-transcribe', 'Whisper'] },
      { title: 'Shot analysis', desc: 'Analyze shots, pacing, scenes and how the product is shown', tools: ['gpt-5.5 Vision', 'Gemini Video'] },
      { title: 'Deconstruct framework', desc: 'Extract the Hook, pain point, selling points, turn and CTA', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'Upload product assets', desc: 'Import your product photos, videos and core selling points', tools: ['File upload', 'GPT vision'] },
      { title: 'Understand product', desc: 'Recognize appearance, use cases, audience and selling points', tools: ['gpt-5.5', 'Gemini 2.5 Pro'] },
      { title: 'Rewrite the script', desc: 'Apply the viral structure to your own product script', tools: ['gpt-5.5', 'Claude Sonnet'] },
      { title: 'Generate storyboard', desc: 'Plan the visuals, captions and actions for every second', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'Generate footage', desc: 'Create new shots and ad clips from your product assets', tools: ['Runway Gen-4.5', 'Veo', 'Seedance'] },
      { title: 'AI voice + captions', desc: 'Generate voiceover, captions, BGM and compose the full video', tools: ['ElevenLabs v3', 'OpenAI TTS', 'FFmpeg'] },
      { title: 'Export multi-platform', desc: 'One-click output tailored for TikTok / Reels / Shorts', tools: ['Remotion', 'Multi-platform'] },
    ] as Step[],
    storyboard: [
      { time: '0:00 - 0:03', shot: 'Fast product close-ups + big caption hook', caption: '"Still struggling with this problem?"' },
      { time: '0:03 - 0:07', shot: 'Real usage scene, product in hand on camera', caption: '"I used it for 7 days — insane results"' },
      { time: '0:07 - 0:12', shot: 'Before/after + animated selling-point captions', caption: '"Three core ingredients, visible results"' },
      { time: '0:12 - 0:16', shot: 'Product lineup + review comment overlay', caption: '"Already my 3rd reorder"' },
      { time: '0:16 - 0:20', shot: 'CTA close-up + limited-offer corner badge', caption: '"Tap the bottom-left to order now"' },
    ] as Shot[],
    script: `[Hook · 0-3s]
Still paying a fortune for influencer ads?
This video was made by AI using your own product assets.

[Pain · 3-7s]
Stock piling up, conversions flat, never enough creatives —
every cross-border seller knows the pain.

[Selling points · 7-13s]
Upload one viral video and your product,
and AI deconstructs the framework, rewrites the copy, generates new clips and voiceover.

[Turn · 13-17s]
No editing, no models, no week-long wait —
a finished ad in 5 minutes for TikTok / Reels / Shorts.

[CTA · 17-20s]
Tap below to generate your first product ad free.`,
  },
  models: {
    eyebrow: 'The AI behind it',
    title: 'Best-in-class models, the right tool for every step',
    subtitle:
      'We automatically route the strongest model at each stage — you never touch the tech, you just get ads that sell.',
    caps: [
      { title: 'Large language models', desc: 'Deconstruct viral frameworks, rewrite copy, generate storyboards' },
      { title: 'Vision understanding', desc: 'Analyze shot pacing and scenes, understand your product and its selling points' },
      { title: 'Video / image generation', desc: 'Generate brand-new ad visuals and clips from your product assets' },
      { title: 'Voice & captions', desc: 'AI voiceover, auto transcription and caption compositing in one click' },
    ],
  },
  pricing: {
    eyebrow: 'Pricing',
    title: 'Start cheap, scale with your business',
    subtitle: 'Pay-as-you-go with zero barrier, subscriptions for better value. Every plan includes the full 12-step workflow.',
    mostPopular: 'Most popular',
    plans: [
      { name: 'Pay as you go', price: '$9.90', unit: '/ video', desc: 'Sellers who post occasionally or want to test the waters', features: ['One full ad per generation', 'Full 12-step workflow', 'Standard resolution export', 'Multi-platform format'], cta: 'Generate per video' },
      { name: 'Growth', price: '$199', unit: '/ month', desc: 'Merchants running ongoing campaigns needing volume', features: ['120 videos per month', 'HD export + no watermark', 'Priority generation queue', 'Viral framework template library', 'Team collaboration seats'], cta: 'Start subscription' },
      { name: 'Team', price: '$399', unit: '/ month', desc: 'Short-video marketing teams and agencies', features: ['500 videos per month', 'API access & batch generation', 'Custom brand styles', 'Dedicated account manager', 'SLA guarantee'], cta: 'Start subscription' },
    ] as MarketingPlan[],
  },
  plans: {
    payg: { name: 'Pay as you go', description: 'Occasional use, buy generations on demand.', cta: 'Buy 1 credit', features: ['1 one-time video generation', 'Full 12-step workflow', '1080P HD export', 'Credits never expire'] },
    growth: { name: 'Growth', description: 'Great value for small and mid-size sellers.', cta: 'Subscribe to Growth', features: ['120 video generations / month', 'Full 12-step workflow', '4K export + no watermark', 'One-click multi-platform', 'Priority generation queue'] },
    team: { name: 'Team', description: 'Team collaboration, massive output.', cta: 'Subscribe to Team', features: ['500 video generations / month', '5 team seats', 'Brand asset library & templates', 'Dedicated success manager', 'API access'] },
  } as Record<'payg' | 'growth' | 'team', AccountPlan>,
  auth: {
    signUpTitle: 'Create your account',
    signInTitle: 'Welcome back',
    signUpSubtitle: 'Sign up, pick a plan, and start turning viral videos into your product ads.',
    signInSubtitle: 'Sign in to view your plan and remaining trial credits.',
    name: 'Name',
    namePlaceholder: 'Your name',
    email: 'Email',
    password: 'Password',
    passwordPlaceholder: 'At least 8 characters',
    signUpBtn: 'Sign up',
    signInBtn: 'Sign in',
    haveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    goSignIn: 'Sign in',
    goSignUp: 'Sign up free',
    signUpFailed: 'Sign up failed',
    signInFailed: 'Sign in failed',
    genericError: 'Something went wrong, please try again',
  },
  account: {
    signOut: 'Sign out',
    greeting: 'Hi, {name}',
    currentPlan: 'Current plan',
    notSubscribed: 'Not subscribed',
    noPlanDesc: "You haven't purchased any plan yet, so trial generation is locked. Choose a plan below to unlock it.",
    remainingCredits: 'Remaining trial credits',
    unlimited: 'Unlimited',
    times: 'credits',
    goCreate: 'Start creating',
    buyToTrial: 'Buy a plan to start your trial.',
    upgradeTitle: 'Upgrade / renew plan',
    chooseTitle: 'Choose a plan to start your trial',
    mostPopular: 'Most popular',
    current: 'Current plan',
    demoNote: 'Payments are securely processed by Stripe. Access is granted only after payment succeeds.',
    perUse: '/ use',
    perMonth: '/ month',
    checkoutSuccess: 'Payment successful! Your plan is now active.',
    checkoutCancelled: 'Checkout was cancelled. You have not been charged.',
    redirecting: 'Redirecting to secure checkout…',
    manageBilling: 'Manage subscription',
    openingPortal: 'Opening billing portal…',
  },
  cta: {
    title: 'Shoot your next viral hit with your own product',
    subtitle:
      'No editing, no influencers, no week-long wait. Upload your assets and get multi-platform product ads in 5 minutes.',
    start: 'Start creating',
    viewPricing: 'View pricing',
  },
  footer: {
    tagline: 'Built for short-video sellers worldwide',
    copyright: '© {year} Clipairy',
    nav: 'Footer navigation',
  },
}

export type Dict = typeof en

// ---------------------------------------------------------------------------
// Simplified Chinese
// ---------------------------------------------------------------------------
const zh: Dict = {
  lang: { label: '语言' },
  nav: { workflow: '工作流', preview: '生成预览', models: 'AI 能力', pricing: '定价' },
  transition: {
    auth: { title: '正在安全登录', description: '正在验证账户并为你准备工作空间…', trust: '你的账户信息已加密保护' },
    checkout: { title: '正在准备安全支付', description: '正在创建你的 Stripe 专属结账页面…', trust: '支付由 Stripe 安全处理' },
    portal: { title: '正在打开账单中心', description: '正在安全连接你的订阅管理设置…', trust: '账单由 Stripe 安全管理' },
    loading: { title: '正在为你准备', description: '正在加载 Clipairy 工作空间…', trust: '安全连接中' },
    errorTitle: '暂时无法完成此操作',
    authError: '请检查登录信息后重试。',
    checkoutError: '暂时无法打开安全支付页面，请重试。',
    retry: '重新尝试',
    home: '返回首页',
  },
  header: {
    signIn: '登录',
    signUp: '免费注册',
    account: '我的账户',
    openMenu: '打开菜单',
    closeMenu: '关闭菜单',
    mainNav: '主导航',
    mobileNav: '移动端导航',
  },
  hero: {
    badge: '为跨境电商与 TikTok Shop 商家打造',
    titleLine1: '一键把爆款视频结构',
    titleHighlight: '变成你的产品广告',
    subtitle:
      '上传一条对标爆款视频，再上传你的产品素材。AI 自动拆解爆款框架、改写文案、生成新片段、配音合成，5 分钟输出适配 TikTok / Reels / Shorts 的短视频广告。',
    ctaStart: '免费开始创作',
    ctaPreview: '查看生成效果',
    exportTo: '支持导出至',
    phoneAlt: 'Clipairy 生成的竖版产品广告预览',
    phoneBadge: 'AI 生成 · 竖版 9:16',
  },
  studio: {
    title: '三步上传，AI 接管剩下的一切',
    subtitle: '上传参考爆款、上传产品素材、填写卖点，点击生成即可看到 12 步工作流实时运行。',
    upload1Label: '1 · 参考爆款视频',
    upload1Hint: '拖入 TikTok / Reels / Shorts 视频',
    upload2Label: '2 · 你的产品素材',
    upload2Hint: '上传产品图或产品视频',
    upload3Label: '3 · 产品卖点',
    sellingPlaceholder: '例如：植物温和配方、7 天见效、跨境包邮、限时买一送一…',
    uploaded: '已上传',
    creator: {
      characterTitle: '出镜人物', characterDesc: '选择预设人物或上传已获授权的照片，全片将尽量保持同一人物。', characterDrift: 'AI 可能出现轻微脸部或服装漂移', characterSelect: '选择出镜人物', characterAlt: '人物参考', uploadCharacter: '上传我的人物', authorization: '仅限本人或已授权照片 · JPG/PNG/WebP · 10 MB', qualityTitle: '视频品质', qualityNames: { economy: '经济', standard: '标准', premium: '高级' }, qualityDescriptions: { economy: '快速低成本，适合测试创意', standard: '清晰度与成本平衡，适合日常发布', premium: '更强运动与画面表现，适合重点广告' }, per8: '每 8 秒', credits: '个额度', modelApprox: '模型约', estimate: '当前 {duration} 秒预计消耗 {credits} 个额度，视频模型约 ${cost}；不含分镜图、语音、存储及失败重试。',
    },
    gateAnonTitle: '登录后购买方案即可试用生成',
    gateAnonDesc: '试用功能仅对拥有有效方案的用户开放。请先登录或注册。',
    gateNoPlanTitle: '购买方��后即可解锁试用次数',
    gateNoPlanDesc: '你当前没有可用次数。选择任意方案后即可开始生成，用完即止。',
    buyPlan: '去购买方案',
    durationLabel: '视频时长',
    secondsUnit: '秒',
    durationHint: '每条成片只扣 1 次；长视频会自动组合多个 AI 片段。',
    aspectRatioLabel: '画面比例',
    portrait: '竖屏',
    landscape: '横屏',
    statusIdle: '准备就绪，点击生成开始 12 步自动化流程',
    statusRunning: '正在处理…',
    statusDone: '生成完成！向下查看脚本、分镜与视频预览',
    stepStatus: { done: '完成', processing: '处理中', waiting: '等待中' },
    statusError: '生成失败',
    retry: '重试',
    errorTitle: '出错了',
    errorDesc: '生成未能完成，请重试。',
    sceneLabel: '场景 ',
    voiceoverHeading: 'AI 配音',
    creditsLabel: '剩余次数：',
    unlimited: '不限',
    regenerate: '再生成一次',
    generate: '生成视频',
    generating: '生成中…',
    workflowHeading: '12 步自动化工作流',
    resultsPlaceholder: '生成结果（脚本 / 分镜 / 视频预览）将在流程完成后显示在这里',
    resultBadge: '生成完成',
    resultTitle: '你的产品广告已就绪',
    scriptHeading: '改写后的广告脚本',
    storyboardHeading: '分镜列表',
    captionLabel: '字幕：',
    videoAlt: 'AI 生成的竖版产品广��视频预览',
    exportButton: '导出成片',
    steps: [
      { title: '上传参考视频', desc: '导入你想对标的 TikTok / Reels / Shorts 爆款视频', tools: ['上传组件', 'S3 / R2 / Supabase Storage'] },
      { title: '视频预处理', desc: '自动拆分音频、画面帧与原始字幕轨道', tools: ['FFmpeg', 'MoviePy'] },
      { title: '提取文案', desc: '把口播、旁白、字幕全部转写成文本', tools: ['gpt-4o-transcribe', 'Whisper'] },
      { title: '画面分解', desc: '���析镜头、节奏、场景与产品展示方式', tools: ['gpt-5.5 Vision', 'Gemini Video'] },
      { title: '拆解爆款框架', desc: '提取 Hook、痛点、卖点、转折与 CTA 结构', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: '上传产品素材', desc: '导入你的产品图、产品视频与核心卖点', tools: ['文件上传', 'GPT 视觉理解'] },
      { title: '产品素材理解', desc: '识别产品外观、使用场景、人群与卖点', tools: ['gpt-5.5', 'Gemini 2.5 Pro'] },
      { title: '改写文案再创作', desc: '把爆款结构套用到你自己的产品脚本上', tools: ['gpt-5.5', 'Claude Sonnet'] },
      { title: '生成分镜脚本', desc: '规划每一秒�����画面、字幕与动作', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: '结合素材生片', desc: '基于产品素材生成新画面与广告片段', tools: ['Runway Gen-4.5', 'Veo', 'Seedance'] },
      { title: 'AI 配音 + 字幕合成', desc: '生成口播、字幕、BGM 并合成完整视频', tools: ['ElevenLabs v3', 'OpenAI TTS', 'FFmpeg'] },
      { title: '导出多平台短视频', desc: '一键输出适配 TikTok / Reels / Shorts 的成片', tools: ['Remotion', '多平台适配'] },
    ],
    storyboard: [
      { time: '0:00 - 0:03', shot: '产品特写快切 + 大字幕 Hook', caption: '"你还在为这个问题头疼吗?"' },
      { time: '0:03 - 0:07', shot: '真实使用场景，手持产品出镜', caption: '"我用了 7 天，效果绝了"' },
      { time: '0:07 - 0:12', shot: '前后对比 + 卖点动态字幕', caption: '"三大核心成分，肉眼可见"' },
      { time: '0:12 - 0:16', shot: '产品排列展示 + 好评弹幕', caption: '"已经回购第 3 次了"' },
      { time: '0:16 - 0:20', shot: 'CTA 特写 + 限时优惠角标', caption: '"点击左下角，立即下单"' },
    ],
    script: `【Hook · 0-3s】
你还在花大价钱找达人拍广告吗?
这条视频,是 AI 用你的产品素材做出来的。

【痛点 · 3-7s】
库存压着、转化上不去、素材永远不够用——
每一个跨境卖家都懂的痛。

【卖点 · 7-13s】
上传一条爆款、上传你的产品,
AI 自动拆框架、改文案、生成新片段并配音。

【转折 · 13-17s】
不用剪辑、不用找模特、不用等一周,
5 分钟出片,适配 TikTok / Reels / Shorts。

【CTA · 17-20s】
点击下方,免费生成你的第一条产品广告。`,
  },
  models: {
    eyebrow: '背后的 AI 能力',
    title: '聚合业界顶尖模型，为每一步选最合适的工具',
    subtitle: '我们在不同环节自动调度最强模型，你无需关心技术细节，只管拿到能出单的广告。',
    caps: [
      { title: '大语言模型', desc: '拆解爆款框架、改写文案、生成分镜脚本' },
      { title: '视觉理解', desc: '分析镜头节奏、场景，理解你的产品外观与卖点' },
      { title: '视频 / 图像生成', desc: '基于产品素材生成全新广告画面与片段' },
      { title: '语音与字幕', desc: 'AI 配音、自动转写与字幕合成，一键成片' },
    ],
  },
  pricing: {
    eyebrow: '定价',
    title: '低价起步，随生意规模增长',
    subtitle: '按次付费零门槛，订阅制更划算。所有方案都包含完整 12 步生成流程。',
    mostPopular: '最受欢迎',
    plans: [
      { name: '按次付费', price: '$9.90', unit: '/ 条视频', desc: '偶尔出片、想先试试效果的卖家', features: ['单条完整广告成片', '12 步全流程处理', '标准清晰度导出', '多平台格式适配'], cta: '按次生成' },
      { name: '增长订阅', price: '$199', unit: '/ 月', desc: '持续投放、需要大量素材的商家', features: ['每月 120 条视频额度', '高清导出 + 去水印', '优先生成队列', '爆款框架模板库', '团队协作席位'], cta: '开始订阅' },
      { name: '团队版', price: '$399', unit: '/ 月', desc: '短视频营销团队与代运营机构', features: ['每月 500 条视频额度', 'API 接入与批量生成', '品牌风格自定义', '专属客户经理', 'SLA 保障'], cta: '开始订阅' },
    ],
  },
  plans: {
    payg: { name: '按次付费', description: '偶尔使用，按需购买生成次数。', cta: '购买 1 次', features: ['一次性 1 次视频生成', '全部 12 步智能工作流', '1080P 高清导出', '次数永久有效'] },
    growth: { name: '增长版', description: '中小卖家的高性价比之选。', cta: '订阅增长版', features: ['每月 120 次视频生成', '全部 12 步智能工作流', '4K 超清导出 + 去水印', '多平台一键适配', '优先生成队列'] },
    team: { name: '团队版', description: '团队协作，海量产出。', cta: '订阅团队版', features: ['每月 500 次视频生成', '5 个团队席位', '品牌素材库与模板', '专属客户成功经理', 'API 接入支持'] },
  },
  auth: {
    signUpTitle: '创建你的账户',
    signInTitle: '欢迎回来',
    signUpSubtitle: '注册后选择方案，即可开始把爆款视频变成你的产品广告。',
    signInSubtitle: '登录以查看你的方案与剩余试用次数。',
    name: '昵称',
    namePlaceholder: '你的名字',
    email: '邮箱',
    password: '密码',
    passwordPlaceholder: '至少 8 位',
    signUpBtn: '注册',
    signInBtn: '登录',
    haveAccount: '已有账户？',
    noAccount: '还没有账户？',
    goSignIn: '去登录',
    goSignUp: '免费注册',
    signUpFailed: '注册失败',
    signInFailed: '登录失败',
    genericError: '出现错误，请重试',
  },
  account: {
    signOut: '退出登录',
    greeting: '你好，{name}',
    currentPlan: '当前方案',
    notSubscribed: '未订阅',
    noPlanDesc: '你还没有购买任何方案，暂时无法试用生成功能。选择下方方案即可解锁。',
    remainingCredits: '剩余试用次数',
    unlimited: '不限次数',
    times: '次',
    goCreate: '去创作',
    buyToTrial: '购买方案后即���开始试用。',
    upgradeTitle: '升级 / 续费方案',
    chooseTitle: '选择方案开始试用',
    mostPopular: '最受欢迎',
    current: '当前方案',
    demoNote: '支付由 Stripe 安全处理，仅在付款成功后才会开通权益。',
    perUse: '/ 次',
    perMonth: '/ 月',
    checkoutSuccess: '支付成功！你的方案已开通。',
    checkoutCancelled: '已取消支付，未产生任何扣款。',
    redirecting: '正在跳转到安全支付页面…',
    manageBilling: '管理订阅',
    openingPortal: '正在打开账单管理…',
  },
  cta: {
    title: '下一条爆款，用你的产品拍',
    subtitle: '不用剪辑、不用找达人、不用等一周。上传素材，5 分钟拿到多平台产品广告。',
    start: '开始创作',
    viewPricing: '查看定价',
  },
  footer: {
    tagline: '为全球短视频卖家而生',
    copyright: '© {year} Clipairy',
    nav: '页脚导航',
  },
}

// ---------------------------------------------------------------------------
// Bahasa Indonesia
// ---------------------------------------------------------------------------
const id: Dict = {
  lang: { label: 'Bahasa' },
  nav: { workflow: 'Alur Kerja', preview: 'Pratinjau', models: 'Model AI', pricing: 'Harga' },
  transition: {
    auth: { title: 'Sedang masuk dengan aman', description: 'Memverifikasi akun dan menyiapkan ruang kerja Anda…', trust: 'Akun Anda terlindungi' },
    checkout: { title: 'Menyiapkan pembayaran aman', description: 'Membuat sesi pembayaran Stripe pribadi Anda…', trust: 'Diproses dengan aman oleh Stripe' },
    portal: { title: 'Membuka pusat tagihan', description: 'Menghubungkan ke pengaturan langganan Anda dengan aman…', trust: 'Dikelola dengan aman oleh Stripe' },
    loading: { title: 'Sedang menyiapkan', description: 'Memuat ruang kerja Clipairy Anda…', trust: 'Koneksi aman' },
    errorTitle: 'Langkah ini belum dapat diselesaikan',
    authError: 'Periksa detail Anda lalu coba lagi.',
    checkoutError: 'Halaman pembayaran aman tidak dapat dibuka. Silakan coba lagi.',
    retry: 'Coba lagi',
    home: 'Kembali ke beranda',
  },
  header: {
    signIn: 'Masuk',
    signUp: 'Daftar gratis',
    account: 'Akun saya',
    openMenu: 'Buka menu',
    closeMenu: 'Tutup menu',
    mainNav: 'Navigasi utama',
    mobileNav: 'Navigasi seluler',
  },
  hero: {
    badge: 'Dibuat untuk penjual e-commerce lintas negara & TikTok Shop',
    titleLine1: 'Ubah struktur video viral',
    titleHighlight: 'menjadi iklan produkmu',
    subtitle:
      'Unggah satu video referensi viral, lalu aset produkmu. AI membedah kerangka yang menang, menulis ulang naskah, membuat footage baru dan sulih suara — iklan TikTok / Reels / Shorts dalam 5 menit.',
    ctaStart: 'Mulai buat gratis',
    ctaPreview: 'Lihat contoh hasil',
    exportTo: 'Ekspor ke',
    phoneAlt: 'Pratinjau iklan produk vertikal yang dibuat Clipairy',
    phoneBadge: 'Dibuat AI · Vertikal 9:16',
  },
  studio: {
    title: 'Unggah 3 langkah, sisanya AI yang urus',
    subtitle:
      'Tambahkan referensi viral, aset produk, dan poin jual — tekan buat dan lihat alur 12 langkah berjalan secara real time.',
    upload1Label: '1 · Video viral referensi',
    upload1Hint: 'Seret video TikTok / Reels / Shorts',
    upload2Label: '2 · Aset produkmu',
    upload2Hint: 'Unggah foto atau video produk',
    upload3Label: '3 · Poin jual',
    sellingPlaceholder:
      'mis. formula nabati lembut, hasil dalam 7 hari, gratis ongkir global, promo beli 1 gratis 1…',
    uploaded: 'Terunggah',
    creator: {
      characterTitle: 'Talent di layar', characterDesc: 'Pilih preset atau unggah foto berizin. Kami akan menjaga orang yang sama sepanjang video.', characterDrift: 'AI mungkin sedikit mengubah wajah atau pakaian', characterSelect: 'Pilih talent', characterAlt: 'referensi karakter', uploadCharacter: 'Unggah talent saya', authorization: 'Hanya diri sendiri atau foto berizin · JPG/PNG/WebP · 10 MB', qualityTitle: 'Kualitas video', qualityNames: { economy: 'Ekonomis', standard: 'Standar', premium: 'Premium' }, qualityDescriptions: { economy: 'Cepat dan hemat untuk menguji ide', standard: 'Kejernihan dan biaya seimbang', premium: 'Gerakan dan visual terbaik untuk iklan utama' }, per8: 'per 8 dtk', credits: 'kredit', modelApprox: 'model sekitar', estimate: 'Perkiraan {duration} dtk: {credits} kredit, model video sekitar ${cost}; belum termasuk storyboard, suara, penyimpanan, dan percobaan ulang.',
    },
    gateAnonTitle: 'Masuk dan beli paket untuk mencoba generasi',
    gateAnonDesc: 'Uji coba hanya tersedia untuk pengguna dengan paket aktif. Silakan masuk atau daftar dulu.',
    gateNoPlanTitle: 'Beli paket untuk membuka kredit uji coba',
    gateNoPlanDesc: 'Kamu tidak punya kredit. Pilih paket apa saja untuk mulai membuat — kredit terpakai seiring penggunaan.',
    buyPlan: 'Ambil paket',
    durationLabel: 'Durasi video',
    secondsUnit: ' dtk',
    durationHint: 'Setiap video jadi memakai 1 kredit. Video panjang menggabungkan beberapa klip AI.',
    aspectRatioLabel: 'Format video',
    portrait: 'Vertikal',
    landscape: 'Horizontal',
    statusIdle: 'Siap — klik buat untuk memulai otomatisasi 12 langkah',
    statusRunning: 'Memproses…',
    statusDone: 'Selesai! Gulir ke bawah untuk naskah, storyboard, dan pratinjau video',
    stepStatus: { done: 'Selesai', processing: 'Memproses', waiting: 'Menunggu' },
    statusError: 'Pembuatan gagal',
    retry: 'Coba lagi',
    errorTitle: 'Terjadi kesalahan',
    errorDesc: 'Pembuatan tidak dapat diselesaikan. Silakan coba lagi.',
    sceneLabel: 'Adegan ',
    voiceoverHeading: 'Sulih suara AI',
    creditsLabel: 'Sisa kredit:',
    unlimited: 'Tanpa batas',
    regenerate: 'Buat lagi',
    generate: 'Buat video',
    generating: 'Membuat…',
    workflowHeading: 'Alur kerja otomatis 12 langkah',
    resultsPlaceholder: 'Hasilmu (naskah / storyboard / pratinjau video) muncul di sini setelah alur selesai',
    resultBadge: 'Generasi selesai',
    resultTitle: 'Iklan produkmu siap',
    scriptHeading: 'Naskah iklan hasil tulis ulang',
    storyboardHeading: 'Storyboard',
    captionLabel: 'Teks:',
    videoAlt: 'Pratinjau iklan produk vertikal buatan AI',
    exportButton: 'Ekspor hasil akhir',
    steps: [
      { title: 'Unggah video referensi', desc: 'Impor video viral TikTok / Reels / Shorts yang ingin ditiru', tools: ['Pengunggah', 'S3 / R2 / Supabase Storage'] },
      { title: 'Praproses video', desc: 'Pisahkan otomatis audio, frame, dan trek teks asli', tools: ['FFmpeg', 'MoviePy'] },
      { title: 'Ekstrak naskah', desc: 'Transkripsi semua narasi, sulih suara, dan teks menjadi tulisan', tools: ['gpt-4o-transcribe', 'Whisper'] },
      { title: 'Analisis shot', desc: 'Analisis shot, tempo, adegan, dan cara produk ditampilkan', tools: ['gpt-5.5 Vision', 'Gemini Video'] },
      { title: 'Bedah kerangka', desc: 'Ekstrak Hook, pain point, poin jual, twist, dan CTA', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'Unggah aset produk', desc: 'Impor foto, video, dan poin jual utama produkmu', tools: ['Unggah file', 'Visi GPT'] },
      { title: 'Pahami produk', desc: 'Kenali tampilan, use case, audiens, dan poin jual', tools: ['gpt-5.5', 'Gemini 2.5 Pro'] },
      { title: 'Tulis ulang naskah', desc: 'Terapkan struktur viral ke naskah produkmu sendiri', tools: ['gpt-5.5', 'Claude Sonnet'] },
      { title: 'Buat storyboard', desc: 'Rencanakan visual, teks, dan aksi tiap detik', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'Buat footage', desc: 'Hasilkan shot dan klip iklan baru dari aset produk', tools: ['Runway Gen-4.5', 'Veo', 'Seedance'] },
      { title: 'Sulih suara + teks AI', desc: 'Buat sulih suara, teks, BGM, dan susun video lengkap', tools: ['ElevenLabs v3', 'OpenAI TTS', 'FFmpeg'] },
      { title: 'Ekspor multi-platform', desc: 'Output sekali klik untuk TikTok / Reels / Shorts', tools: ['Remotion', 'Multi-platform'] },
    ],
    storyboard: [
      { time: '0:00 - 0:03', shot: 'Close-up produk cepat + hook teks besar', caption: '"Masih pusing dengan masalah ini?"' },
      { time: '0:03 - 0:07', shot: 'Adegan pemakaian nyata, produk di tangan', caption: '"Kupakai 7 hari — hasilnya gila"' },
      { time: '0:07 - 0:12', shot: 'Sebelum/sesudah + teks poin jual animasi', caption: '"Tiga bahan inti, hasil terlihat"' },
      { time: '0:12 - 0:16', shot: 'Jajaran produk + overlay ulasan', caption: '"Sudah beli ulang ke-3 kali"' },
      { time: '0:16 - 0:20', shot: 'Close-up CTA + badge promo terbatas', caption: '"Ketuk kiri bawah untuk pesan sekarang"' },
    ],
    script: `[Hook · 0-3s]
Masih bayar mahal untuk iklan influencer?
Video ini dibuat AI dengan aset produkmu sendiri.

[Masalah · 3-7s]
Stok menumpuk, konversi datar, materi tak pernah cukup —
setiap penjual lintas negara paham betul rasanya.

[Poin jual · 7-13s]
Unggah satu video viral dan produkmu,
AI membedah kerangka, menulis ulang naskah, membuat klip baru dan sulih suara.

[Twist · 13-17s]
Tanpa edit, tanpa model, tanpa nunggu seminggu —
iklan jadi dalam 5 menit untuk TikTok / Reels / Shorts.

[CTA · 17-20s]
Ketuk di bawah untuk membuat iklan produk pertamamu gratis.`,
  },
  models: {
    eyebrow: 'AI di baliknya',
    title: 'Model terbaik di kelasnya, alat tepat untuk tiap langkah',
    subtitle: 'Kami otomatis memilih model terkuat di tiap tahap — kamu tak perlu urus teknis, cukup dapat iklan yang menjual.',
    caps: [
      { title: 'Model bahasa besar', desc: 'Bedah kerangka viral, tulis ulang naskah, buat storyboard' },
      { title: 'Pemahaman visual', desc: 'Analisis tempo shot dan adegan, pahami produk dan poin jualnya' },
      { title: 'Generasi video / gambar', desc: 'Buat visual dan klip iklan baru dari aset produkmu' },
      { title: 'Suara & teks', desc: 'Sulih suara AI, transkripsi otomatis, dan penyusunan teks sekali klik' },
    ],
  },
  pricing: {
    eyebrow: 'Harga',
    title: 'Mulai murah, tumbuh bersama bisnismu',
    subtitle: 'Bayar per pakai tanpa hambatan, langganan lebih hemat. Semua paket mencakup alur 12 langkah lengkap.',
    mostPopular: 'Paling populer',
    plans: [
      { name: 'Bayar per pakai', price: '$9.90', unit: '/ video', desc: 'Penjual yang sesekali posting atau ingin coba dulu', features: ['Satu iklan penuh per generasi', 'Alur 12 langkah lengkap', 'Ekspor resolusi standar', 'Format multi-platform'], cta: 'Buat per video' },
      { name: 'Growth', price: '$199', unit: '/ bulan', desc: 'Pedagang kampanye rutin yang butuh volume', features: ['120 video per bulan', 'Ekspor HD + tanpa watermark', 'Antrean generasi prioritas', 'Perpustakaan templat viral', 'Kursi kolaborasi tim'], cta: 'Mulai langganan' },
      { name: 'Tim', price: '$399', unit: '/ bulan', desc: 'Tim marketing video pendek dan agensi', features: ['500 video per bulan', 'Akses API & generasi massal', 'Gaya brand kustom', 'Manajer akun khusus', 'Jaminan SLA'], cta: 'Mulai langganan' },
    ],
  },
  plans: {
    payg: { name: 'Bayar per pakai', description: 'Pemakaian sesekali, beli generasi sesuai kebutuhan.', cta: 'Beli 1 kredit', features: ['1 generasi video sekali beli', 'Alur 12 langkah lengkap', 'Ekspor HD 1080P', 'Kredit tanpa kedaluwarsa'] },
    growth: { name: 'Growth', description: 'Nilai terbaik untuk penjual kecil-menengah.', cta: 'Langganan Growth', features: ['120 generasi video / bulan', 'Alur 12 langkah lengkap', 'Ekspor 4K + tanpa watermark', 'Multi-platform sekali klik', 'Antrean generasi prioritas'] },
    team: { name: 'Tim', description: 'Kolaborasi tim, output besar.', cta: 'Langganan Tim', features: ['500 generasi video / bulan', '5 kursi tim', 'Perpustakaan aset & templat brand', 'Manajer sukses khusus', 'Akses API'] },
  },
  auth: {
    signUpTitle: 'Buat akunmu',
    signInTitle: 'Selamat datang kembali',
    signUpSubtitle: 'Daftar, pilih paket, dan mulai ubah video viral jadi iklan produkmu.',
    signInSubtitle: 'Masuk untuk melihat paket dan sisa kredit uji cobamu.',
    name: 'Nama',
    namePlaceholder: 'Namamu',
    email: 'Email',
    password: 'Kata sandi',
    passwordPlaceholder: 'Minimal 8 karakter',
    signUpBtn: 'Daftar',
    signInBtn: 'Masuk',
    haveAccount: 'Sudah punya akun?',
    noAccount: 'Belum punya akun?',
    goSignIn: 'Masuk',
    goSignUp: 'Daftar gratis',
    signUpFailed: 'Pendaftaran gagal',
    signInFailed: 'Gagal masuk',
    genericError: 'Terjadi kesalahan, coba lagi',
  },
  account: {
    signOut: 'Keluar',
    greeting: 'Hai, {name}',
    currentPlan: 'Paket saat ini',
    notSubscribed: 'Belum berlangganan',
    noPlanDesc: 'Kamu belum membeli paket apa pun, jadi uji coba terkunci. Pilih paket di bawah untuk membukanya.',
    remainingCredits: 'Sisa kredit uji coba',
    unlimited: 'Tanpa batas',
    times: 'kredit',
    goCreate: 'Mulai buat',
    buyToTrial: 'Beli paket untuk mulai uji coba.',
    upgradeTitle: 'Tingkatkan / perpanjang paket',
    chooseTitle: 'Pilih paket untuk mulai uji coba',
    mostPopular: 'Paling populer',
    current: 'Paket saat ini',
    demoNote: 'Pembayaran diproses dengan aman oleh Stripe. Akses hanya diberikan setelah pembayaran berhasil.',
    perUse: '/ pakai',
    perMonth: '/ bulan',
    checkoutSuccess: 'Pembayaran berhasil! Paket Anda kini aktif.',
    checkoutCancelled: 'Checkout dibatalkan. Anda tidak dikenai biaya.',
    redirecting: 'Mengalihkan ke checkout aman…',
    manageBilling: 'Kelola langganan',
    openingPortal: 'Membuka portal penagihan…',
  },
  cta: {
    title: 'Bikin hit viral berikutnya dengan produkmu sendiri',
    subtitle:
      'Tanpa edit, tanpa influencer, tanpa nunggu seminggu. Unggah asetmu dan dapatkan iklan produk multi-platform dalam 5 menit.',
    start: 'Mulai buat',
    viewPricing: 'Lihat harga',
  },
  footer: {
    tagline: 'Dibuat untuk penjual video pendek di seluruh dunia',
    copyright: '© {year} Clipairy',
    nav: 'Navigasi footer',
  },
}

// ---------------------------------------------------------------------------
// Thai
// ---------------------------------------------------------------------------
const th: Dict = {
  lang: { label: 'ภาษา' },
  nav: { workflow: 'ขั้นตอน', preview: 'ตัวอย่าง', models: 'โมเดล AI', pricing: 'ราคา' },
  transition: {
    auth: { title: 'กำลังเข้าสู่ระบบอย่างปลอดภัย', description: 'กำลังตรวจสอบบัญชีและเตรียมพื้นที่ทำงานของคุณ…', trust: 'บัญชีของคุณได้รับการปกป้อง' },
    checkout: { title: 'กำลังเตรียมการชำระเงิน', description: 'กำลังสร้างหน้าชำระเงิน Stripe ส่วนตัวของคุณ…', trust: 'ประมวลผลอย่างปลอดภัยโดย Stripe' },
    portal: { title: 'กำลังเปิดศูนย์การเรียกเก็บเงิน', description: 'กำลังเชื่อมต่อการตั้งค่าการสมัครสมาชิกอย่างปลอดภัย…', trust: 'จัดการอย่างปลอดภัยโดย Stripe' },
    loading: { title: 'กำลังเตรียมให้คุณ', description: 'กำลังโหลดพื้นที่ทำงาน Clipairy…', trust: 'การเชื่อมต่อปลอดภัย' },
    errorTitle: 'ยังไม่สามารถดำเนินการนี้ได้',
    authError: 'โปรดตรวจสอบข้อมูลแล้วลองอีกครั้ง',
    checkoutError: 'ไม่สามารถเปิดหน้าชำระเงินที่ปลอดภัยได้ โปรดลองอีกครั้ง',
    retry: 'ลองอีกครั้ง',
    home: 'กลับหน้าหลัก',
  },
  header: {
    signIn: 'เข้าสู่ระบบ',
    signUp: 'สมัครฟรี',
    account: 'บัญชีของฉัน',
    openMenu: 'เปิดเมนู',
    closeMenu: 'ปิดเมนู',
    mainNav: 'เมนูหลัก',
    mobileNav: 'เมนูมือถือ',
  },
  hero: {
    badge: 'สร้างมาเพื่อผู้ขายอีคอมเมิร์ซข้ามพรมแดนและ TikTok Shop',
    titleLine1: 'เปลี่ยนโครงสร้างวิดีโอไวรัล',
    titleHighlight: 'ให้เป็นโฆษณาสินค้าของคุณ',
    subtitle:
      'อัปโหลดวิดีโอไวรัลอ้างอิงหนึ่งคลิป แล้วตามด้วยสื่อสินค้าของคุณ AI จะถอด���ครงสร้างที่ปัง เขียนสคริปต์ใหม่ สร้างฟุตเทจและพากย์เสียง — ได้โฆษณา TikTok / Reels / Shorts ใน 5 นาที',
    ctaStart: 'เริ่มสร้างฟรี',
    ctaPreview: 'ดูตัวอย่างผลลัพธ์',
    exportTo: 'ส่งออกไปยัง',
    phoneAlt: 'ตัวอย่างโฆษณาสินค้าแนวตั้งที่สร้างโดย Clipairy',
    phoneBadge: 'สร้างด้วย AI · แนวตั้ง 9:16',
  },
  studio: {
    title: 'อัปโหลด 3 ขั้นตอน ที่เหลือให้ AI จัดการ',
    subtitle: 'ใส่วิดีโออ้างอิง สื่อสินค้า และจุดขาย แล้วกดสร้าง ดูขั้นตอน 12 ขั้นทำงานแบบเรียลไทม์',
    upload1Label: '1 · วิดีโอไวรัลอ้างอิง',
    upload1Hint: 'ลากวิดีโอ TikTok / Reels / Shorts มาวาง',
    upload2Label: '2 · สื่อสินค้าของคุณ',
    upload2Hint: 'อัปโหลดรูปหรือวิดีโอสินค้า',
    upload3Label: '3 · จุดขาย',
    sellingPlaceholder: 'เช่น สูตรพืชอ่อนโยน เห็นผลใน 7 วัน ส่งฟรีทั่วโลก โปรซื้อ 1 แถม 1…',
    uploaded: 'อัปโหลดแล้ว',
    gateAnonTitle: 'เข้าสู่ระบบและซื้อแพ็กเกจเพื่อทดลองสร้าง',
    gateAnonDesc: 'การทดลองใช้เปิดเฉพาะผู้ใช้ที่มีแพ็กเกจใช้งานอยู่ กรุณาเข้าสู่ระบบหรือสมัครก่อน',
    gateNoPlanTitle: 'ซื้อแพ็กเกจเพื่อปลดล็อกจำนวนครั้งทดลอง',
    gateNoPlanDesc: 'คุณยังไม่มีจำนวนครั้งที่ใช้ได้ เลือกแพ็กเกจใดก็ได้เพื่อเริ่มสร้าง ใช้แล้วหมดไป',
    buyPlan: 'ไปซื้อแพ็กเกจ',
    durationLabel: 'ความยาววิดีโอ',
    secondsUnit: ' วิ',
    durationHint: 'วิดีโอสำเร็จแต่ละรายการใช้ 1 เครดิต วิดีโอยาวจะรวมคลิป AI หลายคลิป',
    aspectRatioLabel: 'รูปแบบวิดีโอ',
    portrait: 'แนวตั้ง',
    landscape: 'แนวนอน',
    statusIdle: 'พร้อมแล้ว คลิกสร้างเพื่อเริ่มขั้นตอนอัตโนมัติ 12 ขั้น',
    statusRunning: 'กำลังประมวลผล…',
    statusDone: 'เสร็จแล้ว! เลื่อนลงเพื่อดูสคริปต์ สตอรีบอร์ด และตัวอย่างวิดีโอ',
    stepStatus: { done: 'เสร็จ', processing: 'กำลังทำ', waiting: 'รอ' },
    statusError: 'สร้างไม่สำเร็จ',
    retry: 'ลองอีกครั้ง',
    errorTitle: 'เกิดข้อผิดพลาด',
    errorDesc: 'ไม่สามารถสร้างวิดีโอได้ กรุณาลองใหม่อีกครั้ง',
    sceneLabel: 'ฉาก ',
    voiceoverHeading: 'เสียงพากย์ AI',
    creditsLabel: 'จำนวนครั้งคงเหลือ:',
    unlimited: 'ไม่จำกัด',
    regenerate: 'สร้างอีกครั้ง',
    generate: 'สร้างวิดีโอ',
    generating: 'กำลังสร้าง…',
    workflowHeading: 'ขั้นตอนอัตโนมัติ 12 ขั้น',
    resultsPlaceholder: 'ผลลัพธ์ (สคริปต์ / สตอรีบอร์ด / ตัวอย่างวิดีโอ) จะแสดงที่นี่เมื่อขั้นตอนเสร็จ',
    resultBadge: 'สร้างเสร็จแล้ว',
    resultTitle: 'โฆษณาสินค้าของคุณพร้อมแล้ว',
    scriptHeading: 'สคริปต์โฆษณาที่เขียนใหม่',
    storyboardHeading: 'สตอรีบอร์ด',
    captionLabel: 'คำบรรยาย:',
    videoAlt: 'ตัวอย่างโฆษณาสินค้าแนวตั้งที่สร้างโดย AI',
    exportButton: 'ส่งออกวิดีโอ',
    steps: [
      { title: 'อัปโหลดวิดีโออ้างอิง', desc: 'นำเข้าวิดีโอไวรัล TikTok / Reels / Shorts ที่อยากอ้างอิง', tools: ['ตัวอัปโหลด', 'S3 / R2 / Supabase Storage'] },
      { title: 'ประมวลผลวิดีโอเบื้องต้น', desc: 'แยกเสียง เฟรมภาพ และแทร็กคำบรรยายต้นฉบับอัตโนมัติ', tools: ['FFmpeg', 'MoviePy'] },
      { title: 'ดึงข้อความ', desc: 'ถอดเสียงพูด เสียงบรรยาย และคำบรรยายทั้งหมดเป็นข้อความ', tools: ['gpt-4o-transcribe', 'Whisper'] },
      { title: 'วิเคราะห์ช็อต', desc: 'วิเคราะห์ช็อต จังหวะ ฉาก และวิธีนำเสนอสินค้า', tools: ['gpt-5.5 Vision', 'Gemini Video'] },
      { title: 'ถอดโครงสร้างที่ปัง', desc: 'ดึง Hook จุดเจ็บปวด จุดขาย จุดพลิก และ CTA', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'อัปโหลดสื่อสินค้า', desc: 'นำเข้ารูป วิดีโอ และจุดขายหลักของสินค้า', tools: ['อัปโหลดไฟล์', 'GPT วิชวล'] },
      { title: 'เข้าใจสินค้า', desc: 'ระบุรูปลักษณ์ การใช้งาน กลุ่มเป้าหมาย และจุดขาย', tools: ['gpt-5.5', 'Gemini 2.5 Pro'] },
      { title: 'เขียนสคริปต์ใหม่', desc: 'นำโครงสร้างไวรัลมาใช้กับสคริปต์สินค้าของคุณ', tools: ['gpt-5.5', 'Claude Sonnet'] },
      { title: 'สร้างสตอรีบอร์ด', desc: 'วางแผนภาพ คำบรรยาย และแอ็กชันทุกวินาที', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'สร้างฟุตเทจ', desc: 'สร้างช็อตและคลิปโฆษณาใหม่จากสื่อสินค้า', tools: ['Runway Gen-4.5', 'Veo', 'Seedance'] },
      { title: 'พากย์เสียง + คำบรรยาย AI', desc: 'สร้างเสียงพากย์ คำบรรยาย เพลงประกอบ และรวมเป็นวิดีโอ', tools: ['ElevenLabs v3', 'OpenAI TTS', 'FFmpeg'] },
      { title: 'ส่งออกหลายแพลตฟอร์ม', desc: 'ส่งออกคลิกเดียวสำหรับ TikTok / Reels / Shorts', tools: ['Remotion', 'หลายแพลตฟอร์ม'] },
    ],
    storyboard: [
      { time: '0:00 - 0:03', shot: 'ภาพสินค้าใกล้ตัดเร็ว + hook ตัวอักษรใหญ่', caption: '"ยังปวดหัวกับปัญหานี้อยู่ไหม?"' },
      { time: '0:03 - 0:07', shot: 'ฉากใช้งานจริง ถือสินค้าเข้ากล้อง', caption: '"ใช้มา 7 วัน ผลลัพธ์สุดปัง"' },
      { time: '0:07 - 0:12', shot: 'ก่อน/หลัง + คำบรรยายจุดขายเคลื่อนไหว', caption: '"สามส่วนผสมหลัก เห็นผลด้วยตา"' },
      { time: '0:12 - 0:16', shot: 'จัดเรียงสินค้า + รีวิวลอย', caption: '"ซื้อซ้ำครั้งที่ 3 แล้ว"' },
      { time: '0:16 - 0:20', shot: 'ภาพ CTA ใกล้ + ป้ายโปรจำกัดเวลา', caption: '"แตะมุมซ้ายล่าง สั่งเลย"' },
    ],
    script: `[Hook · 0-3s]
ยังจ่ายแพงจ้างอินฟลูฯ ถ่ายโฆษณาอยู่ไหม?
คลิปนี้ AI สร้างจากสื่อสินค้าของคุณเอง

[จุดเจ็บปวด · 3-7s]
สต็อกค้าง ยอดแปลงไม่ขึ้น สื่อไม่เคยพอ —
ผู้ขายข้ามพรมแดนทุกคนเข้าใจดี

[จุดขาย · 7-13s]
อัปโหลดคลิปไวรัลหนึ่งคลิปและสินค้าของคุณ
AI ถอดโครงสร้าง เขียนสคริปต์ใหม่ สร้างคลิปใหม่และพากย์เสียง

[จุดพลิก · 13-17s]
ไม่ต้องตัดต่อ ไม่ต้องหานางแบบ ไม่ต้องรอเป็นสัปดาห์ —
ได้คลิปใน 5 นาที สำหรับ TikTok / Reels / Shorts

[CTA · 17-20s]
แตะด้านล่างเพื่อสร้างโฆษณาสินค้าชิ้นแรกของคุณฟรี`,
  },
  models: {
    eyebrow: 'AI เบื้องหลัง',
    title: 'รวมโมเดลชั้นนำ เลือกเครื่องมือที่เหมาะกับทุกขั้นตอน',
    subtitle: 'เราเลือกโมเดลที่แข็งแกร่งที่สุดในแต่ละขั้นให้อัตโนมัติ คุณไม่ต้องยุ่งกับเทคนิค แค่ได้โฆษณาที่ขายได้',
    caps: [
      { title: 'โมเดลภาษาขนาดใหญ่', desc: 'ถอดโครงสร้างไวรัล เขียนสคริปต์ใหม่ สร้างสตอรีบอร์ด' },
      { title: 'ความเข้าใจภาพ', desc: 'วิเคราะห์จังหวะช็อตและฉาก เข้าใจสินค้าและจุดขาย' },
      { title: 'สร้างวิดีโอ / รูปภาพ', desc: 'สร้างภาพและคลิปโฆษณาใหม่จากสื่อสินค้าของคุณ' },
      { title: 'เสียงและคำบรรยาย', desc: 'พากย์เสียง AI ถอดข้อความอัตโนมัติ และรวมคำบรรยายในคลิกเดียว' },
    ],
  },
  pricing: {
    eyebrow: 'ราคา',
    title: 'เริ่มต้นราคาถูก เติบโตไปกับธุรกิจ',
    subtitle: 'จ่ายตามครั้งไม่มีข้อจำกัด สมัครสมาชิกคุ้มกว่า ทุกแพ็กเกจรวมขั้นต���น 12 ขั้นเต็มรูปแบบ',
    mostPopular: 'ยอดนิยม',
    plans: [
      { name: 'จ่ายตามครั้ง', price: '$9.90', unit: '/ วิดีโอ', desc: 'ผู��ขายที่โพสต์เป็นครั้งคราวหรืออยากลองก่อน', features: ['โฆษณ���เต็มหนึ่งชิ้นต่อการสร้าง', 'ขั้นตอน 12 ขั้นครบ', 'ส่งออกความละเอียดมาตรฐาน', 'รองรับหลายแพลตฟอร์ม'], cta: 'สร้างตามครั้ง' },
      { name: 'Growth', price: '$199', unit: '/ เดือน', desc: 'ร้านค้าที่ยิงโฆษณาต่อเนื่องและต้องการปริมาณ', features: ['120 วิดีโอต่อเดือน', 'ส่งออก HD + ไม่มีลายน้ำ', 'คิวสร้างลำดับต้น', 'คลังเทมเพลตไวรัล', 'ที่นั่งทำงานเป็นทีม'], cta: 'เริ่มสมัครสมาชิก' },
      { name: 'ทีม', price: '$399', unit: '/ เดือน', desc: 'ทีมการตลาดวิดีโอสั้นและเอเจนซี', features: ['500 วิดีโอต่อเดือน', 'เข้าถึง API และสร้างจำนวนมาก', 'ปรับสไตล์แบรนด์เอง', 'ผู้จัดการบัญชีเฉพาะ', 'รับประกัน SLA'], cta: 'เริ่มสมัครสมาชิก' },
    ],
  },
  plans: {
    payg: { name: 'จ่ายตามครั้ง', description: 'ใช้เป็นครั้งคราว ซื้อจำนวนครั้งตามต้องการ', cta: 'ซื้อ 1 ครั้ง', features: ['สร้างวิดีโอ 1 ครั้งแบบซื้อครั้งเดียว', 'ขั้นตอน 12 ขั้นครบ', 'ส่งออก HD 1080P', 'จำนวนครั้งไม่หมดอายุ'] },
    growth: { name: 'Growth', description: 'คุ้มค่าที่สุดสำหรับผู้ขายรายเล็กถึงกลาง', cta: 'สมัคร Growth', features: ['สร้างวิดีโอ 120 ครั้ง / เดือน', 'ขั้นตอน 12 ขั้นครบ', 'ส่งออก 4K + ไม่มีลายน้ำ', 'หลายแพลตฟอร์มคลิกเดียว', 'คิวสร้างลำดับต้น'] },
    team: { name: 'ทีม', description: 'ทำงานเป็นทีม ผลิตจำนวนมาก', cta: 'สมัครแพ็กเกจทีม', features: ['สร้างวิดีโอ 500 ครั้ง / เดือน', 'ที่นั่งทีม 5 ที่', 'คลังสื่อและเทมเพลตแบรนด์', 'ผู้จัดการดูแ����เฉพาะ', 'รองรับการเชื่อม API'] },
  },
  auth: {
    signUpTitle: 'สร้างบัญชีของคุณ',
    signInTitle: 'ยินดีต้อนรับกลับ',
    signUpSubtitle: 'สมัคร เลือกแพ็กเกจ แล้วเริ่มเปลี่ยนวิดีโอไวรัลเป็นโฆษณาสินค้าของคุณ',
    signInSubtitle: 'เข้าสู่ระบบเพื่อดูแพ็กเกจและจำนวนครั้งทดลองที่เหลือ',
    name: 'ชื่อ',
    namePlaceholder: 'ชื่อของคุณ',
    email: 'อีเมล',
    password: 'ร��ัสผ่าน',
    passwordPlaceholder: 'อย่างน้อย 8 ตัว',
    signUpBtn: 'สมัคร',
    signInBtn: 'เข้าสู่ระบบ',
    haveAccount: 'มีบัญชีอยู่แล้ว?',
    noAccount: 'ยังไม่มีบัญชี?',
    goSignIn: 'เข้าสู่ระบบ',
    goSignUp: 'สมัครฟรี',
    signUpFailed: 'สมัครไม่สำเร็จ',
    signInFailed: 'เข้าสู่ระบบไม่สำเร็จ',
    genericError: 'เกิดข้อผิดพลาด กรุณาลองใหม่',
  },
  account: {
    signOut: 'ออกจากระบบ',
    greeting: 'สวัสดี {name}',
    currentPlan: 'แพ็กเกจปัจจุบัน',
    notSubscribed: 'ยังไม่ได้สมัคร',
    noPlanDesc: 'คุณยังไม่ได้ซื้อแพ็กเกจใด ๆ จึงยังทดลองสร้างไม่ได้ เลือกแพ็กเกจด้านล่างเพื่อปลดล็อก',
    remainingCredits: 'จำนวนครั้งทดลองที่เหลือ',
    unlimited: 'ไม่จำกัด',
    times: 'ครั้ง',
    goCreate: 'ไปสร้าง',
    buyToTrial: 'ซื้อแพ็กเกจเพื่อเริ่มทดลอง',
    upgradeTitle: 'อัปเกรด / ต่ออายุแพ็กเกจ',
    chooseTitle: 'เลือกแพ็กเกจเพื่อเริ่มทดลอง',
    mostPopular: 'ยอดนิยม',
    current: 'แพ็กเกจปัจจุบัน',
    demoNote: 'การชำระเงินดำเนินการอย่างปลอดภัยโดย Stripe จะเปิดใช้งานสิทธิ์หลังชำระเงินสำเร็จเท่านั้น',
    perUse: '/ ครั้ง',
    perMonth: '/ เดือน',
    checkoutSuccess: 'ชำระเงินสำเร็จ! แพ็กเกจของคุณเปิดใช้งานแล้ว',
    checkoutCancelled: 'ยกเลิกการชำระเงินแล้ว ยังไม่มีการเรียกเก็บเงิน',
    redirecting: 'กำลังนำไปยังหน้าชำระเงินที่ปลอดภัย…',
    manageBilling: 'จัดการการสมัครสมาชิก',
    openingPortal: 'กำลังเปิดพอร์ทัลการเรียกเก็บเงิน…',
  },
  cta: {
    title: 'คลิปปังคลิปต่อไป ถ่ายด้วยสินค้าของคุณ',
    subtitle:
      'ไม่ต้องตัดต่อ ไม่ต้องหาอินฟลูฯ ไม่ต้องรอเป็นสัปดาห์ อัปโหลดสื่อแล้วได้โฆษณาสินค้าหลายแพลตฟอร์มใน 5 นาที',
    start: 'เริ่มสร้าง',
    viewPricing: 'ดูราคา',
  },
  footer: {
    tagline: 'สร้างเพื่อผู้ขายวิดีโอสั้นทั่วโลก',
    copyright: '© {year} Clipairy',
    nav: 'เมนูส่วนท้าย',
  },
}

// ---------------------------------------------------------------------------
// Vietnamese
// ---------------------------------------------------------------------------
const vi: Dict = {
  lang: { label: 'Ngôn ngữ' },
  nav: { workflow: 'Quy trình', preview: 'Xem trước', models: 'Mô hình AI', pricing: 'Bảng giá' },
  transition: {
    auth: { title: 'Đang đăng nhập an toàn', description: 'Đang xác minh tài khoản và chuẩn bị không gian làm việc…', trust: 'Tài khoản của bạn được bảo vệ' },
    checkout: { title: 'Đang chuẩn bị thanh toán', description: 'Đang tạo phiên thanh toán Stripe riêng tư của bạn…', trust: 'Được Stripe xử lý an toàn' },
    portal: { title: 'Đang mở trung tâm thanh toán', description: 'Đang kết nối an toàn tới cài đặt đăng ký…', trust: 'Được Stripe quản lý an toàn' },
    loading: { title: 'Đang chuẩn bị', description: 'Đang tải không gian làm việc Clipairy…', trust: 'Kết nối an toàn' },
    errorTitle: 'Chưa thể hoàn tất bước này',
    authError: 'Vui lòng kiểm tra thông tin và thử lại.',
    checkoutError: 'Không thể mở trang thanh toán an toàn. Vui lòng thử lại.',
    retry: 'Thử lại',
    home: 'Về trang chủ',
  },
  header: {
    signIn: 'Đăng nhập',
    signUp: 'Đăng ký miễn phí',
    account: 'Tài khoản',
    openMenu: 'Mở menu',
    closeMenu: 'Đóng menu',
    mainNav: 'Điều hướng chính',
    mobileNav: 'Điều hướng di động',
  },
  hero: {
    badge: 'Dành cho nhà bán hàng TMĐT xuyên biên giới & TikTok Shop',
    titleLine1: 'Biến cấu trúc video viral',
    titleHighlight: 'thành quảng cáo sản phẩm của bạn',
    subtitle:
      'Tải lên một video viral tham chiếu, rồi đến tư liệu sản phẩm. AI phân tích khung viral, viết lại kịch bản, tạo cảnh quay và lồng tiếng mới — quảng cáo TikTok / Reels / Shorts trong 5 phút.',
    ctaStart: 'B��t đầu miễn phí',
    ctaPreview: 'Xem kết quả mẫu',
    exportTo: 'Xuất sang',
    phoneAlt: 'Xem trước quảng cáo sản phẩm dọc do Clipairy tạo',
    phoneBadge: 'Tạo bởi AI · Dọc 9:16',
  },
  studio: {
    title: 'Tải lên 3 bước, AI lo phần còn lại',
    subtitle: 'Thêm video viral tham chiếu, tư liệu sản phẩm và điểm bán — nhấn tạo và xem quy trình 12 bước chạy theo thời gian thực.',
    upload1Label: '1 · Video viral tham chiếu',
    upload1Hint: 'Kéo video TikTok / Reels / Shorts vào',
    upload2Label: '2 · Tư liệu sản phẩm',
    upload2Hint: 'Tải ảnh hoặc video sản phẩm',
    upload3Label: '3 · Điểm bán',
    sellingPlaceholder: 'vd: công thức thực vật dịu nhẹ, hiệu quả sau 7 ngày, miễn phí ship toàn cầu, mua 1 tặng 1…',
    uploaded: 'Đã tải lên',
    gateAnonTitle: 'Đăng nhập và mua gói để dùng thử tạo video',
    gateAnonDesc: 'Dùng thử chỉ dành cho người dùng có gói đang hoạt động. Vui lòng đăng nhập hoặc đăng ký trước.',
    gateNoPlanTitle: 'Mua gói để mở khóa lượt dùng thử',
    gateNoPlanDesc: 'Bạn chưa có lượt khả dụng. Chọn bất kỳ gói nào để bắt đầu tạo — lượt sẽ dùng dần đến hết.',
    buyPlan: 'Mua gói',
    durationLabel: 'Thời lượng video',
    secondsUnit: ' giây',
    durationHint: 'Mỗi video hoàn chỉnh dùng 1 lượt. Video dài sẽ ghép nhiều đoạn AI.',
    aspectRatioLabel: 'Định dạng video',
    portrait: 'Dọc',
    landscape: 'Ngang',
    statusIdle: 'Sẵn sàng — nhấn tạo để bắt đầu quy trình tự động 12 bước',
    statusRunning: 'Đang xử lý…',
    statusDone: 'Xong! Cuộn xuống để xem kịch bản, storyboard và bản xem trước video',
    stepStatus: { done: 'Xong', processing: 'Đang xử lý', waiting: 'Chờ' },
    statusError: 'Tạo thất bại',
    retry: 'Thử lại',
    errorTitle: 'Đã xảy ra lỗi',
    errorDesc: 'Không thể hoàn tất việc tạo video. Vui lòng thử lại.',
    sceneLabel: 'Cảnh ',
    voiceoverHeading: 'Lồng tiếng AI',
    creditsLabel: 'Lượt còn lại:',
    unlimited: 'Không giới hạn',
    regenerate: 'Tạo lại',
    generate: 'Tạo video',
    generating: 'Đang tạo…',
    workflowHeading: 'Quy trình tự động 12 bước',
    resultsPlaceholder: 'Kết quả (kịch bản / storyboard / xem trước video) sẽ hiện ở đây khi quy trình hoàn tất',
    resultBadge: 'Tạo hoàn tất',
    resultTitle: 'Quảng cáo sản phẩm của bạn đã sẵn sàng',
    scriptHeading: 'Kịch bản quảng cáo đã viết lại',
    storyboardHeading: 'Storyboard',
    captionLabel: 'Phụ đề:',
    videoAlt: 'Xem trước quảng cáo sản phẩm dọc do AI tạo',
    exportButton: 'Xuất bản hoàn chỉnh',
    steps: [
      { title: 'Tải video tham chiếu', desc: 'Nhập video viral TikTok / Reels / Shorts bạn muốn học theo', tools: ['Trình tải lên', 'S3 / R2 / Supabase Storage'] },
      { title: 'Tiền xử lý video', desc: 'Tự động tách âm thanh, khung hình và phụ đề gốc', tools: ['FFmpeg', 'MoviePy'] },
      { title: 'Trích xuất lời thoại', desc: 'Chuyển toàn bộ lời nói, lồng tiếng và phụ đề thành văn bản', tools: ['gpt-4o-transcribe', 'Whisper'] },
      { title: 'Phân tích c��nh quay', desc: 'Phân tích cảnh, nhịp độ, bối cảnh và cách trình bày sản phẩm', tools: ['gpt-5.5 Vision', 'Gemini Video'] },
      { title: 'Giải mã khung viral', desc: 'Trích xuất Hook, điểm đau, điểm bán, cú lật và CTA', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'Tải tư liệu sản phẩm', desc: 'Nhập ảnh, video và điểm bán cốt lõi của sản phẩm', tools: ['Tải tệp', 'Thị giác GPT'] },
      { title: 'Hiểu sản phẩm', desc: 'Nhận diện diện mạo, tình huống dùng, đối tượng và điểm bán', tools: ['gpt-5.5', 'Gemini 2.5 Pro'] },
      { title: 'Viết lại kịch bản', desc: 'Áp dụng cấu trúc viral vào kịch bản sản phẩm của bạn', tools: ['gpt-5.5', 'Claude Sonnet'] },
      { title: 'Tạo storyboard', desc: 'Lên kế hoạch hình ảnh, phụ đề và hành động từng giây', tools: ['gpt-5.5', 'Claude', 'Gemini'] },
      { title: 'Tạo cảnh quay', desc: 'Tạo cảnh và clip quảng cáo mới từ tư liệu sản phẩm', tools: ['Runway Gen-4.5', 'Veo', 'Seedance'] },
      { title: 'Lồng tiếng + phụ đề AI', desc: 'Tạo lồng tiếng, phụ đề, nh��c nền và ghép video hoàn chỉnh', tools: ['ElevenLabs v3', 'OpenAI TTS', 'FFmpeg'] },
      { title: 'Xuất đa nền tảng', desc: 'Xuất một chạm cho TikTok / Reels / Shorts', tools: ['Remotion', 'Đa nền tảng'] },
    ],
    storyboard: [
      { time: '0:00 - 0:03', shot: 'Cận cảnh sản phẩm cắt nhanh + hook chữ lớn', caption: '"Vẫn đau đầu với vấn đề này sao?"' },
      { time: '0:03 - 0:07', shot: 'Cảnh dùng thật, cầm sản phẩm trước máy quay', caption: '"Dùng 7 ngày — kết quả cực đỉnh"' },
      { time: '0:07 - 0:12', shot: 'Trước/sau + phụ đề điểm bán động', caption: '"Ba thành phần cốt lõi, thấy rõ bằng mắt"' },
      { time: '0:12 - 0:16', shot: 'Dàn sản phẩm + đánh giá nổi', caption: '"Đã mua lại lần thứ 3"' },
      { time: '0:16 - 0:20', shot: 'Cận cảnh CTA + nhãn ưu đãi giới hạn', caption: '"Chạm góc dưới trái để đặt ngay"' },
    ],
    script: `[Hook · 0-3s]
Vẫn chi bộn tiền thuê KOL quay quảng cáo?
Video này do AI tạo từ chính tư liệu sản phẩm của bạn.

[Điểm đau · 3-7s]
Tồn kho chất đống, chuyển đổi giậm chân, thiếu tư liệu triền miên —
nhà bán xuyên biên giới nào cũng thấm.

[Điểm bán · 7-13s]
Tải lên một video viral và sản phẩm của bạn,
AI giải mã khung, viết lại lời, tạo clip mới và lồng tiếng.

[Cú lật · 13-17s]
Không cần dựng, không cần mẫu, không chờ cả tuần —
quảng cáo hoàn chỉnh trong 5 phút cho TikTok / Reels / Shorts.

[CTA · 17-20s]
Chạm bên dưới để tạo quảng cáo sản phẩm đầu tiên miễn phí.`,
  },
  models: {
    eyebrow: 'AI phía sau',
    title: 'Mô hình hàng đầu, đúng công cụ cho mỗi bước',
    subtitle: 'Chúng tôi tự động chọn mô hình mạnh nhất ở mỗi giai đoạn — bạn không cần lo kỹ thuật, chỉ cần quảng cáo bán được hàng.',
    caps: [
      { title: 'Mô hình ngôn ngữ lớn', desc: 'Giải mã khung viral, viết lại lời, tạo storyboard' },
      { title: 'Hiểu hình ảnh', desc: 'Phân tích nhịp cảnh và bối cảnh, hiểu sản phẩm và điểm bán' },
      { title: 'Tạo video / hình ảnh', desc: 'Tạo hình ảnh và clip quảng cáo mới từ tư liệu sản phẩm' },
      { title: 'Giọng nói & phụ đề', desc: 'Lồng tiếng AI, tự động chép lời và ghép phụ đề chỉ một chạm' },
    ],
  },
  pricing: {
    eyebrow: 'Bảng giá',
    title: 'Bắt đầu rẻ, lớn cùng doanh nghiệp',
    subtitle: 'Trả theo lượt không rào cản, đăng ký gói tiết kiệm hơn. Mọi gói đều có đủ quy trình 12 bước.',
    mostPopular: 'Phổ biến nhất',
    plans: [
  { name: 'Trả theo lượt', price: '$9.90', unit: '/ video', desc: 'Người bán đăng thỉnh thoảng hoặc muốn thử trước', features: ['Một quảng cáo hoàn chỉnh mỗi l��n tạo', 'Đủ quy trình 12 bước', 'Xuất độ phân giải tiêu chuẩn', 'Định dạng đa nền tảng'], cta: 'Tạo theo lượt' },
  { name: 'Growth', price: '$199', unit: '/ tháng', desc: 'Nhà bán chạy chiến dịch liên tục, cần số lượng', features: ['120 video mỗi tháng', 'Xuất HD + không watermark', 'Hàng đợi ưu tiên', 'Thư viện mẫu viral', 'Ghế cộng tác nhóm'], cta: 'Bắt đầu đăng ký' },
  { name: 'Nhóm', price: '$399', unit: '/ tháng', desc: 'Đội marketing video ngắn và agency', features: ['500 video mỗi tháng', 'Truy cập API & tạo hàng loạt', 'Tùy chỉnh phong cách thương hiệu', 'Quản lý tài khoản riêng', 'Cam kết SLA'], cta: 'Bắt đầu đăng ký' },
    ],
  },
  plans: {
    payg: { name: 'Trả theo lượt', description: 'Dùng thỉnh thoảng, mua lượt tạo theo nhu cầu.', cta: 'Mua 1 lượt', features: ['1 lượt tạo video mua một lần', 'Đủ quy trình 12 bước', 'Xuất HD 1080P', 'Lượt không hết hạn'] },
    growth: { name: 'Growth', description: 'Giá trị tốt cho nhà bán nh�� và vừa.', cta: 'Đăng ký Growth', features: ['120 lượt tạo video / tháng', 'Đủ quy trình 12 bư��c', 'Xuất 4K + không watermark', 'Đa nền tảng một chạm', 'Hàng đợi ưu tiên'] },
    team: { name: 'Nhóm', description: 'Cộng tác nhóm, sản lượng lớn.', cta: 'Đăng ký gói Nhóm', features: ['500 lượt tạo video / tháng', '5 ghế nhóm', 'Thư viện tư liệu & mẫu thương hiệu', 'Quản lý thành công riêng', 'Hỗ trợ tích hợp API'] },
  },
  auth: {
    signUpTitle: 'Tạo tài khoản của bạn',
    signInTitle: 'Chào mừng trở lại',
    signUpSubtitle: 'Đăng ký, chọn gói và bắt đầu biến video viral thành quảng cáo sản phẩm.',
    signInSubtitle: 'Đăng nhập để xem gói và số lượt dùng thử còn lại.',
    name: 'Tên',
    namePlaceholder: 'Tên của bạn',
    email: 'Email',
    password: 'Mật khẩu',
    passwordPlaceholder: 'Ít nhất 8 ký tự',
    signUpBtn: 'Đăng ký',
    signInBtn: 'Đăng nhập',
    haveAccount: 'Đã có tài khoản?',
    noAccount: 'Chưa có tài khoản?',
    goSignIn: 'Đăng nhập',
    goSignUp: 'Đăng ký miễn phí',
    signUpFailed: 'Đăng ký thất bại',
    signInFailed: 'Đăng nhập thất bại',
    genericError: 'Đã xảy ra lỗi, vui lòng thử lại',
  },
  account: {
    signOut: 'Đăng xuất',
    greeting: 'Chào {name}',
    currentPlan: 'Gói hiện tại',
    notSubscribed: 'Chưa đăng ký',
    noPlanDesc: 'Bạn chưa mua gói nào nên chưa thể dùng thử tạo video. Chọn gói b��n dưới để mở khóa.',
    remainingCredits: 'Lượt dùng thử còn lại',
    unlimited: 'Không giới hạn',
    times: 'lượt',
    goCreate: 'Đi tạo',
    buyToTrial: 'Mua gói để bắt đầu dùng thử.',
    upgradeTitle: 'Nâng cấp / gia hạn gói',
    chooseTitle: 'Chọn gói để bắt đầu dùng thử',
    mostPopular: 'Phổ biến nhất',
    current: 'Gói hiện tại',
    demoNote: 'Thanh toán được Stripe xử lý an toàn. Quyền lợi chỉ được cấp sau khi thanh toán thành công.',
    perUse: '/ lượt',
    perMonth: '/ tháng',
    checkoutSuccess: 'Thanh toán thành công! Gói của bạn đã được kích hoạt.',
    checkoutCancelled: 'Đã hủy thanh toán. Bạn chưa bị tính phí.',
    redirecting: 'Đang chuyển đến trang thanh toán an toàn…',
    manageBilling: 'Quản lý đăng ký',
    openingPortal: 'Đang mở cổng thanh toán…',
  },
  cta: {
    title: 'Quay hit viral tiếp theo bằng chính sản phẩm của bạn',
    subtitle:
      'Không dựng, không KOL, không chờ cả tuần. Tải tư liệu lên và nhận quảng cáo sản phẩm đa nền tảng trong 5 phút.',
    start: 'Bắt đầu tạo',
    viewPricing: 'Xem bảng giá',
  },
  footer: {
    tagline: 'Dành cho nhà bán video ngắn toàn cầu',
    copyright: '© {year} Clipairy',
    nav: 'Điều hướng chân trang',
  },
}

export const dictionaries: Record<Locale, Dict> = { en, zh, id, th, vi }
